services:
  - type: web
    name: "barbershop-booking"
    env: "python"
    buildCommand: "sh build.sh"
    startCommand: "gunicorn barbershop.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: "barbershop-db"
          property: "connectionString"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"

databases:
  - name: "barbershop-db"
    plan: "free"
